version: '2'

services:
    boilerplatebackend:
        volumes:
            - .:/boilerplate
            - /backend/node_modules

        build:
            context: ./backend
            dockerfile: ./Dockerfile

        ports:
          - "443:443"
