version: 2.1

commands:
  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi

jobs:
  checkout_code:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/build
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/build
  # TODO - Chrome Tests as well
  firefox_integration_tests:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/build
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      # TODO - switch to cypress.io from selenium
      - run: cd ./mock-backend && npm install
      - run:
          command: cd ./mock-backend && node ./server.js
          background: true
      - run: cd ./frontend && npm install
      - run:
          command: cd ./frontend && npm run local-server
          background: true
      - run: wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:8080/config
      - run: cd ./frontend && npm run integration-tests

workflows:
  version: 2.1
  extension_workflow:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
      - firefox_integration_tests:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
